// Structure des routes pour manipuler les données en Strapi : https://docs.strapi.io/dev-docs/api/rest

GET http://localhost:1337/
###
GET http://localhost:1337/toto/


// JEUX GRATUITS

###
// Créer un jeu gratuit :
POST http://localhost:1337/api/free-games/
content-type: application/json

{
  "name": "Candy Crush",
  "description": "Le but du jeu est de faire écraser des bonbons colorés en associant des combinaisons d'au moins trois bonbons5, afin de remplir l'objectif du niveau et de marquer un maximum de points. Les objectifs peuvent être les suivants : Gagner un nombre de points (niveau 1) ; Enlever toute la gélatine (niveau 6) ; Faire tomber les ingrédients (niveau 11) ; Gagner un nombre de points en un temps limité (niveau 20) ; Récupérer toutes les commandes (niveau 126).",
  "image": "https://www.greatestcoloringbook.com/wp-content/uploads/2020/05/jeux-de-match-3-plus-de-276-jeux-de-match-3-gratuits-sur-pour-jeux-des-differences-gratuit.jpg"
}

###
POST http://localhost:1337/api/free-games/
content-type: application/json

{
  "name": "Bubble Shooter",
  "description": "Le but du jeu est de vider le canon, symbolisé par une flèche violette, en tirant sur des balles identiques. Les points varient en fonction du nombre de balles que vous faites éclater en 1 tir. Les erreurs sont sanctionnées par des points de pénalité et au bout de 5 points, la rangée descend d'1 étage. Plus vous avez éliminé de couleurs et plus le nombre d'étage rajouté est important. Le but principal est d'éliminer toutes les bubbles.",
  "image": "https://image.winudf.com/v2/image1/Y29tLnRpZ2Vyc3R1ZGlvYmcuZ2FtZXMuYnViYmxlc2hvb3Rlcl9zY3JlZW5fMF8xNTQ5MjExMjQ1XzAzMQ/screen-0.jpg?h=710&fakeurl=1&type=.jpg"
}

###
POST http://localhost:1337/api/free-games/
content-type: application/json

{
  "name": "Scrabble",
  "description": "Le but du jeu est de cumuler le plus de points en formant des mots entrecroisés sur une grille de 15×15 cases. Les lettres possèdent des valeurs différentes et les cases, selon leur couleur peuvent multiplier la valeur des lettres (cases bleues) ou des mots (cases rouges).",
  "image": "https://www.greatestcoloringbook.com/wp-content/uploads/2020/05/jouer-au-scrabble-en-ligne-les-meilleurs-sites-et-applis-dedans-jeux-enfant-gratuit-en-ligne.jpeg"
}

###
// Récupérer tous les jeux gratuits :
GET http://localhost:1337/api/free-games/
content-type: application/json

###
// Récupérer un jeu gratuit
GET http://localhost:1337/api/free-games/2
content-type: application/json

###
// Modifier un jeu gratuit
PUT http://localhost:1337/api/free-games/3
content-type: application/json

{
  "data": {
    "name": "Candy Crush Saga"
  }
}


###
// Supprimer un jeu gratuit
DELETE http://localhost:1337/api/free-games/1


// JEUX PAYANTS

###
// Créer un jeu payant :
POST http://localhost:1337/api/official-games/
content-type: application/json
// Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzAxNzkwMjA5LCJleHAiOjE3MDQzODIyMDl9.w5N8wvNofDx20jk1YtpLjoui3jibUfJogH-eCpArYts

{
  "name": "Minecraft",
  "description": "Le joueur sera immergé dans un monde en trois dimensions, de type “bac à sable” (ou “sandbox”), c’est-à-dire qu’il pourra interagir avec le monde, en cassant ou en plaçant des blocs. Dans le mode survie vous devrez récolter des ressources pour survivre face aux squelettes, zombies et autres monstres de Minecraft, ou bien construire dans un monde sans limite généré aléatoirement. Le but étant de tuer l’Enderdragon, un dragon qui se cache dans une autre dimension. Vous pouvez jouer seul ou en multijoueur très facilement. Dans le jeu, vous pouvez également jouer en mode “Créatif” spécialement dédié à la construction d’à peu près tout ce que vous voulez. De ce fait, vous pouvez y créer vos propres objectifs ou bien partager vos créations. Vous battre avec vos amis, ou bien vous allier face aux monstres ! Minecraft n’a aucune limite et c’est ce qui en fait sa beauté.",
  "image": "https://i.pinimg.com/736x/81/61/32/816132e3f5cf75f6ddd44b5f6536cdac.jpg",
  "price": 22.09
}

###
POST http://localhost:1337/api/official-games/
content-type: application/json
// Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzAxNzkwMjA5LCJleHAiOjE3MDQzODIyMDl9.w5N8wvNofDx20jk1YtpLjoui3jibUfJogH-eCpArYts

{
  "name": "Les Sims 4",
  "description": "Les Sims est une simulation de vie proposant de gérer la vie des sims — les habitants de la série Sim City — en leur donnant des directives. Une partie ne se termine jamais car même s'il n'y a plus de sims vivants, le joueur est libre d'en créer de nouveau.",
  "image": "https://2.bp.blogspot.com/-Uh2ioMCTKho/VCFgdwaJR9I/AAAAAAAABOM/PeYJA57xbro/s1600/ts4_google_plus_cover_2120x1192.jpg",
  "price": 7.66
}

###
// Récupérer tous les jeux payants :
GET http://localhost:1337/api/official-games/
content-type: application/json
// Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzAxNzkwMjA5LCJleHAiOjE3MDQzODIyMDl9.w5N8wvNofDx20jk1YtpLjoui3jibUfJogH-eCpArYts

###
// Récupérer un jeu payant
GET http://localhost:1337/api/official-games/3
content-type: application/json
// Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzAxNzkwMjA5LCJleHAiOjE3MDQzODIyMDl9.w5N8wvNofDx20jk1YtpLjoui3jibUfJogH-eCpArYts

###
// Modifier un jeu payant
PUT http://localhost:1337/api/official-games/3
content-type: application/json
// Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzAxNzkwMjA5LCJleHAiOjE3MDQzODIyMDl9.w5N8wvNofDx20jk1YtpLjoui3jibUfJogH-eCpArYts

{
  "data": {
    "name": "Les Sims 3"
  }
}

###
// Supprimer un jeu payant
DELETE http://localhost:1337/api/official-games/1
//content-type: application/json
// Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzAxNzkwMjA5LCJleHAiOjE3MDQzODIyMDl9.w5N8wvNofDx20jk1YtpLjoui3jibUfJogH-eCpArYts


// UTILISATEURS

###
// Rajouter un utilisateur (automatiquement connecté ???) :
POST http://localhost:1337/api/auth/local/register
content-type: application/json

{
  "pseudo": "Toto",
  "email": "toto@gmail.com",
  "password": "asdq37dqqsd7"
}

###
// Rajouter un utilisateur (automatiquement connecté ???) :
POST http://localhost:1337/api/auth/local/register
content-type: application/json

{
  "pseudo": "Tata",
  "email": "tata@gmail.com",
  "password": "asdfqslwjazqsd7"
}
