// Structure des routes pour manipuler les données en Strapi : https://docs.strapi.io/dev-docs/api/rest


### Rajouter un utilisateur (automatiquement connecté) :

POST http://localhost:1337/api/auth/local/register
content-type: application/json

{
  "pseudo": "Toto",
  "email": "toto@gmail.com",
  "password": "asdq37dqqsd7"
}

### Rajouter un utilisateur (automatiquement connecté) :

POST http://localhost:1337/api/auth/local/register
content-type: application/json

{
  "pseudo": "Tata",
  "email": "tata@gmail.com",
  "password": "asdfqslwjazqsd7"
}

### Authentifier un utilisateur (le Token s'affiche ici) :

POST http://localhost:1337/api/auth/local
content-type: application/json

{
  "identifier": "toto@gmail.com",
  "password": "asdq37dqqsd7"
}

// Copier-coler le Token généré dans la variable dans le fichier "officialGamesRequests.http" !

### Deconnecter un utilisateur :

POST http://localhost:1337/api/auth/logout
// Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicHNldWRvIjoiVG90byIsImVtYWlsIjoidG90b0BnbWFpbC5jb20iLCJpYXQiOjE3MDIwNTEwNjl9.mBqmEaBi26egmQRyX5_SrshPOec1SL1G4ZvVRZLy4d8